=== jan-ldwg/site_manager_docs/json_schemas/devices/GET_device_res.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "GET api/v1/devices/{deviceId} RESPONSE",
  "description": "JSON document describing a single device",
  "type": "object",
  "properties": {
    "id": { "description": "", "type": "string", "format": "uuid" },
    "name": { "description": "", "type": ["string", "null"] },
    "deviceTypeId": {
      "description": "Id of the device type. Consists of id of manufacturer followed by id of device type. See documentation for rules.",
      "type": "string",
      "pattern": "^(?=.{1,48}$)(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])?-[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$",
      "maxLength": 48
    },
    "deviceTypeName": {
      "description": "Name of the device as given by manufacturer",
      "type": "string",
      "maxLength": 256
    },
    "manufacturerId": {
      "description": "Id of the manufacturer of the device type.",
      "type": "string",
      "patter": "^(?!.*--)[a-z](?:[a-z-]{0,14}[a-z])$",
      "maxLength": 16
    },
    "manufacturerName": { "description": "", "type": "string" },
    "manufacturerNameShort": { "description": "", "type": "string" },
    "description": { "description": "", "type": ["string", "null"] },
    "serialNumber": { "description": "", "type": ["string", "null"] },
    "siteId": { "description": "", "type": "string", "format": "uuid" },
    "siteName": { "description": "", "type": "string" },
    "buildingId": { "description": "", "type": "string", "format": "uuid" },
    "buildingName": { "description": "", "type": "string" },
    "roomId": { "description": "", "type": "string", "format": "uuid" },
    "roomName": { "description": "", "type": "string" },
    "roomNumber": {
      "description": "Number of the room",
      "type": ["string", "null"],
      "maxLength": 16
    },
    "rackId": { "description": "", "type": "string", "format": "uuid" },
    "rackName": { "description": "", "type": "string" },
    "ports": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "description": "", "type": "string", "format": "uuid" },
          "portTypeId": {
            "description": "",
            "type": "string",
            "format": "uuid"
          },
          "portTypeName": {
            "description": "Name of the port, as printed on the device.",
            "type": "string"
          },
          "portTypeDirection": {
            "description": "Direction of the port type. See documentation for explainations of the possible values.",
            "enum": [
              "IN",
              "OUT",
              "INOUT",
              "BIDI",
              "UP",
              "DOWN",
              "FRONT",
              "BACK"
            ]
          },
          "connectorId": {
            "description": "Id of the connector.",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          },
          "connectorName": { "description": "", "type": "string" },
          "connectorGender": {
            "description": "",
            "enum": ["MALE", "FEMALE", "HERMA"]
          },
          "connectorIcon": {
            "description": "Icon for use with this connector. These can be fetched as SVG icons from /icons/{id}.svg",
            "type": "string",
            "pattern": "^[A-Za-z0-9](?:[A-Za-z0-9]|[_.](?=[A-Za-z0-9]))*_(?:f|m|h)$"
          }
        },
        "required": [
          "id",
          "portTypeId",
          "portTypeName",
          "portTypeDirection",
          "connectorId",
          "connectorName",
          "connectorIcon"
        ],
        "additionalProperties": false
      }
    },
    "moduleSlots": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "description": "", "type": "string", "format": "uuid" },
          "moduleSlotTypeId": {
            "description": "",
            "type": "string",
            "format": "uuid"
          },
          "moduleSlotTypeName": {
            "description": "Name of the module slot, as labeled on the device.",
            "type": "string"
          },
          "module": { "type": "object" }
        },
        "required": ["id", "moduleSlotTypeId", "moduleSlotTypeName", "module"],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "id",
    "name",
    "deviceTypeId",
    "deviceTypeName",
    "manufacturerId",
    "manufacturerName",
    "manufacturerNameShort",
    "description",
    "serialNumber",
    "siteId",
    "siteName",
    "buildingId",
    "buildingName",
    "roomId",
    "roomName",
    "roomNumber",
    "rackId",
    "rackName",
    "ports",
    "moduleSlots"
  ],
  "additionalProperties": false
}

=== jan-ldwg/site_manager_docs/json_examples/devices/POST_devices_res.json
{
  "id": "f0492dbe-d74c-4b1e-9315-1afc78511927",
  "name": "Device",
  "deviceTypeId": "lawo-power-core-rev-3",
  "deviceTypeName": "Power Core Rev.3",
  "manufacturerId": "lawo",
  "manufacturerName": "Lawo AG",
  "manufacturerNameShort": "Lawo",
  "description": "Audio DSP for playout",
  "serialNumber": "12345",
  "siteId": "7829eb19-3f4f-4935-b5c3-2ce3aef53de2",
  "siteName": "Stuttgart",
  "buildingId": "fb20f42d-f53b-45d5-81a0-4865e88ac25e",
  "buildingName": "HDHF",
  "roomId": "d6f7e684-d06e-4002-9c4e-fdd34040715c",
  "roomName": "Regie",
  "roomNumber": "104/1",
  "rackId": "a4d350f3-719e-4b10-a1f9-de9630b2560e",
  "rackName": "Rack",
  "ports": [
    {
      "id": "315bb8d4-c40c-432b-906c-d0ba9fcb2d83",
      "portTypeId": "045758c9-71bf-4888-99c1-94d23456e4fd",
      "portTypeName": "WCLK IN",
      "portTypeDirection": "IN",
      "connectorId": "BNC_f",
      "connectorName": "BNC 75 Ohm female",
      "connectorGender": "FEMALE",
      "connectorIcon": "BNC_f"
    }
  ],
  "moduleSlots": [
    {
      "id": "2e042ef9-3695-4333-9975-0ba83e511bdc",
      "moduleSlotTypeId": "f2181ebd-71a9-47db-9ff6-0bbee73d1032",
      "moduleSlotTypeName": "dwc0",
      "module": {
        "id": "4e1b0966-1660-482d-8212-f1a69f457702",
        "moduleTypeId": "lawo-98160-61",
        "moduleTypeName": "981/60-61",
        "manufacturerId": "lawo",
        "manufacturerName": "Lawo AG",
        "manufacturerNameShort": "Lawo",
        "ports": [
          {
            "id": "8892e87d-a60f-479e-a438-dc1bd56c68c3",
            "portTypeId": "db961f94-4ec0-41e8-9528-082a8ab1001c",
            "portTypeName": "",
            "portTypeDirection": "UP",
            "connectorId": "RJ45_f",
            "connectorName": "RJ45 female",
            "connectorGender": "FEMALE",
            "connectorIcon": "RJ45_f"
          }
        ],
        "moduleSlots": []
      }
    }
  ]
}
